WELCOME_MSG = 'Привет. Это бот теста Бека на депрессию. Ответив на вопросы, вы узнаете степень своей депрессии. ' \
              'Для начала теста воспользуйтесь командой /depress'
EXIT_TEST_MSG = 'Выйти'
TEST_INTERRUPTED_MSG = 'Тест прерван'
TEST_RESTART_MSG = 'Начать заново'
TEST_RESTARTED_MSG = 'Тест перезапущен'
AVAIBLE_COMMANDS_MSG = 'Доступные комманды'
WRONG_ANSWER_MSG = 'Ошибка. Выберите ответ из предложенных.'
COUNTING_POINTS_ERROR_MSG = 'Ошибка, неверно посчитаны баллы'
TEST_RESULT_MSG = 'Ваш результат: %s\n'
NO_DEPRESS_MSG = 'Депрессивные симптомы отсутствуют.'
LIGHT_DEPRESS_MSG = 'Легкая депрессия'
AVERAGE_DEPRESS_MSG = 'Умеренная депрессия'
SEVERE_DEPRESS_MSG = 'Выраженная депрессия'
HARD_DEPRESS_MSG = 'Тяжелая депрессия'
