WELCOME_MSG = 'Привет. Это бот теста Бека на депрессию. Ответив на вопросы вы узнаете степень своей депрессии. Для начала теста воспользуйтесь командой /depress'
EXIT_TEST_MSG = 'Выйти'
TEST_INTERRUPTED_MSG = 'Тест прерван'
TEST_RESTART_MSG = 'Начать заново'
TEST_RESTARTED_MSG = 'Тест перезапущен'
AVAIBLE_COMMANDS_MSG = 'Доступные комманды'
WRONG_ANSWER_MSG = 'Ошибка. Выберите ответ из предложенных.'